# The purpose of this script is to remove all files generated from running wasm-bindgen.
# It can be used as part of the WASM build process which allows running the game in a web browser.
# Remove all files generated from running wasm-bindgen for the WASM build process.

$files = @(
    "./www/public/mooplas.d.ts",
    "./www/public/mooplas.js",
    "./www/public/mooplas.wasm.d.ts",
    "./www/public/mooplas.wasm"
)

Write-Host "Removing files generated by wasm-bindgen..."
foreach ($file in $files)
{
    if (Test-Path -Path $file)
    {
        Remove-Item -Path $file -Force
        Write-Host "Removed $file"
    }
    else
    {
        Write-Host "$file does not exist"
    }
}