#!/usr/bin/env bash
# The purpose of this script is to remove all files generated from running wasm-bindgen.
# It can be used as part of the WASM build process which allows running the game in a web browser.
# Remove all files generated from running wasm-bindgen for the WASM build process.

set -euo pipefail
IFS=$'\n\t'

FILES=(
  "./www/public/mooplas_game.d.ts"
  "./www/public/mooplas_game.js"
  "./www/public/mooplas_game_bg.wasm.d.ts"
  "./www/public/mooplas_game_bg.wasm"
)

echo "Removing files generated by wasm-bindgen..."
for file in "${FILES[@]}"; do
  if [[ -e "$file" ]]; then
    rm -f -- "$file"
    echo "Removed $file"
  else
    echo "$file does not exist"
  fi
done

